### ISSUE TITLE
is the bot actually deploying it? 🤔🤔🤔 

### ISSUE THREAD

**Issue by Ali-A-Koye** [sumaya99/lastportfolio#1]

**Comment by sumaya99** [comment]
yea

**Comment by Ali-A-Koye** [comment]
its not showing me any errors , thats a good sign even for a blank page 😂😂 ... seems incomplete , will check it out when its done :) 




![image](https://user-images.githubusercontent.com/66186390/118084600-ac924e80-b3c9-11eb-8109-6eff03d4e47f.png)

**Comment by sumaya99** [comment]
hahaha , here it's the latest one , https://lastportfolio-2-b0wygabzf-sumaya99.vercel.app/#/ , tho i have to redeploy it again bcz there's a lot of changes , need to add more of ma projects there , rate it : )

**Comment by Ali-A-Koye** [comment]
oh you re opened it :D , well its great ... however i give you 6-7/10 , and give 4 to mine no worries .. its not like i have a good one 

i just did a quick check and didn't like 2-3 things and i may have been wrong!! 

1- the images of the apps are alot and smaller in small screens ... i prefer a slider that user can easily swipe image by image , that will increase the quality of images and make it clear 

2- your github , its like hewr's ... recoded basically do that to everyone , if i want to check your github .. i come and see how many repo s you have , and believe me : everyone is to lazy to check the repo s and see which is worth checking ... show only what you want others to see in very few amount of time :) 
![image](https://user-images.githubusercontent.com/66186390/118396353-dc568600-b657-11eb-88f5-a077fd91883c.png)

3- you can't have a cv of everything , i usually don't include languages like java or c++ in a web position .. include only those that is related to the job , make it dynamic so you dont have to deploy it anytime you apply for a job :) :)

**Comment by sumaya99** [comment]
I couldn't get it , like you mean , create a separated cv for each of ma fields? , bcz i was about to include , all the 2d animation and graphic  desigs , apps , ui/ux designs in one portfolio 😁

**Comment by sumaya99** [comment]
And..... about the screens that u mentioned , i'll make it clickable when the user touchs it it will go to a shared adobe xd screens so no need for a slider

**Comment by Ali-A-Koye** [comment]
not each of your fields , only related ones ... Web development CV , Mobile App  Development CV , Graphic Designer CV , only in the big picture .. and Adobe XD or not , its ugly ¯\_(ツ)_/¯

**Comment by sumaya99** [comment]
I got it , thank ya 🤟🏻
